const header = {
  uz: "uz",
  ru: "ru",
  en: "en",
  action: "boshqa",
  create: "yaratish",
  delete: "o'chirish",
  update: "tahrirlash",
  basket: "Savat",
  transfer: "O'tkazish",
  login: {
    welcome: "Arifsolarga xush kelibsiz",
    title: "Login",
    password: "Parol",
    enter: "kirish",
    wrongpasswor: "Foydalanuvchi nomi yoki paroli noto'g'ri! Iltimos, qayta urinib ko'ring",
  },

  alerts: {
    password_incorreect:
      "parol noto'g'ri: parol kamida bitta katta harf, belgi va raqamdan iborat bo'lishi kerak, 6 dan 30 ta belgigacha bo'lishi kerak",
    confirmdelete: "O'chirishni istaysizmi?",
    ok: "ok",
    no: "bekor qilish",
    inputError: "Kirish maydonchalari bo'sh bo'lmasligi kerak",
    nodelete: "ruxsat yo'q",
    deleted: "Muvaffaqiyatli o'chirildi",
    added: "Savatga muvaffaqiyatli qo'shildi",
    edited: "Muvaffaqiyatli o'zgartirildi",
    slownetwork: "Internet aloqangiz yo'q yoki juda sekin",
    warning: "nimadir noto'g'ri bo'ldi, iltimos, qayta urinib ko'ring",
  },

  sidebar: {
    banners: "Bannerlar",
    cars: "Avtomobillar",
    answers: "Savol & Javoblar",
    reviews: "Sharhlar",
    leeds: "Leedlar",
    admins: "Boshqaruvchilar",
    mobile: "mobil",
    type: "turi",
    exit: "Chiqish",
    role: "rol",
  },

  home: {
    start_time: "boshlanish vaqti",
    end_time: "tugash vaqti",
    budget: "byudjet",
    clients: "mijozlar",
    total_profit: "umumiy foyda",
    expenses: "xarajatlar",
  },

  table: {
    fuel_type: "yoqilg'i turi",
    max_speed: "maksimal tezlik",
    place: "joy",
    tinting: "tonirovka",
    baggage: "yuk",
    conditioner: "konditsioner",
    false: "mavjud emas",
    true: "mavjud",

    lang: "til",
    star: "yulduz",
    from: "dan",
    ordered: "buyurtma berildi",
    moving_from_country: "mamlakatdan ko'chirish",
    entered_to_country: "mamlakatga kirish",
    delivered: "yetkazib berildi",
    creator: "yaratuvchi",
    types: "ko'rinish filtri",
    all: "hammasi",
    by_category: "kategoriya bo'yicha",
    by_client: "mijoz bo'yicha",
    by_fesclient: "FES mijoz bo'yicha",
    complated: "yakunlandi",
    active: "faol",
    kurs: "kurs",
    shipment_id: "yuk tashish identifikatori",
    custom_date: "maxsus vaqt",
    residual_amount: "qisqa ma'lumot",
    complated_amount: "batafsil ma'lumot",
    complated: "yakunlandi",
    image: "rasm",
    exist: "mavjud",
    deliver_name: " yetkazib beruvchining ismi",
    deliver_phone: "yetkazib beruvchining telefoni",
    truck_number: "asosiy",
    add_shipment: "Yuk tashishni qo'shish",
    name: "ism",
    sale: "sotish",
    titile: "sarlovha",
    sale_cost: "sotish narxi",
    sale_amount: "chegirma foizi",
    subtitle: "quyi sarlavha",
    info: "ma'lumot",
    created_at: "yaratilgan vaqt",
    amount: "miqdor",
    overall_price: "ozuqaviy qiymati",
    payed_price: "tarkibi",
    status: "holat",
    country: "Kategoriya",
    country_number: " buyurtma raqami",
    id: "identifikator",
    inn: "INN",
    total_amount: "umumiy miqdor",
    type: "Avtomobil turi",
    seria_id: "quyi",
    sum: "Summa",
    dollar: "valyutada",
    stock_id: "ombor identifikatori",
    price: "quyi sarlavha",
    client_id: "mijoz identifikatori",
    new_price: "narx",
    direction: "yo'nalish",
    product_name: "mahsulot nomi",
    client_name: "mijozning ismi",
    client_number: "mijoz raqami",
    phone_number: "telefon raqami",
    additional_info: "qo'shimcha ma'lumot",
    expenses_name: "xarajatlar nomi",
    rows_per_page: "Sahifadagi qatorlar",
    date: "vaqt",
    status: "holat",
    direction: "yo'nalish",
    rejected: "rad etildi",
    accepted: "qabul qilindi",
    reject: "rad etish",
    accept: "qabul qilish",
    pending: "kutish",
    warehouse: "Ombor",
    employee: "xodim",
    location: "joylashuv",
  },

  modal: {
    add: "Qo'shish",
    addProduct: {
      addproduct: "Mahsulot qo'shish",
      editproduct: "Mahsulotni tahrirlash",
      count: "soni",
      kg: "kg",
      liter: "litr",
      meter: "metr",
      sale: "sotish",
      addtocart: "Savatga qo'shish",
      sale_product: "Mahsulotni sotish",
      total_price: "Umumiy narx",
    },
    addDeliver: {
      adddeliver: "Kategoriya qo'shish",
      editdeliver: "Kategoriyani tahrirlash",
    },
    addOrder: {
      addorder: "Buyurtma qo'shish",
      editorder: "Buyurtmani tahrirlash",
    },
    addWarehouse: {
      title: "Brend qo'shish",
      edit: "Brendni tahrirlash",
      transfer_from_werhouse: "Asosiy ombordan o'tkazish",
      transfer_to_werhouse: "Ombordan omborga o'tkazish",
    },
    addClient: {
      title: "Mijoz qo'shish",
      edit: "Mijozni tahrirlash",
    },
    addExpenses: {
      title: "Xarajatlarni qo'shish",
      edit: "Xarajatlarni tahrirlash",
    },
    addIncome: {
      title: "Daromad qo'shish",
      edit: "Daromadni tahrirlash",
    },
    addCategory: {
      title: "Kategoriya qo'shish",
      edit: "Kategoriyani tahrirlash",
      category: "Kategoriya",
      subcategory: "Pastki kategoriya",
      subtitle: "Pastki kategoriyani qo'shish",
      subedit: "Pastki kategoriyani tahrirlash",
    },
    addCompany: {
      title: "Kompaniya qo'shish",
      edit: "Kompaniyani tahrirlash",
      category: "Kompaniya",
      subcategory: "hisob raqami",
      subtitle: "Kompaniya hisobini qo'shish",
      subedit: "Kompaniya hisobini tahrirlash",
    },
    fes: {
      AddModal: {
        type: "turi",
        power: "Quvvat",
        fes_client: "FES Mijozini qo'shish",
        fes_application: "FES Arizasini qo'shish",
        edit_fes_application: "FES Arizasini tahrirlash",
        edit_fes_client: "FES Mijozini tahrirlash",
      },
    },
  },
};

export default header;
