const header = {
  uz: "uz",
  ru: "ru",
  en: "en",
  dashboard: "Boshqaruv paneli",
  action: "boshqa",
  create: "yaratish",
  delete: "o'chirish",
  update: "tahrirlash",
  stores: "Bikelar",
  sales_count: "Sotish soni",
  product_count: "Mahsulotlar soni",
  product_amount: "Mahsulotlar miqdori",
  avarage_check: "O'rtacha Chek",
  all_product_count: "Barcha mahsulotlar",
  top_store: "Eng ko'p sotadigan bikelar",
  top_product: "Eng ko'p sotiladigan mahsulotlar",
  basket: "Savatcha",
  transfer: "O'tkazish",
  login: {
    welcome: "Iysor ga xush kelibsiz!",
    password: "Parol",
    title: "Login",
    enter: "kirish",
    wrongpasswor: "Foydalanuvchi nomi yoki parol noto'g'ri! Qayta urinib ko'ring",
  },

  alerts: {
    password_incorreect:
      "parol noto'g'ri: parol kamida bitta bosh harf, belgi va raqamdan iborat bo'lishi kerak 6 dan 30 gacha belgidan iborat bo'lishi kerak",
    confirmdelete: "Haqiqatan ham oʻchirib tashlamoqchimisiz ?",
    ok: "tasdiqlash",
    no: "bekor qilish",
    inputError: "Inputlar bo'sh malumot qo'shilmadi",
    nodelete: "o'chirishga ruxsat yo'q",
    deleted: "Muvaffaqiyatli o'chirildi",
    added: "Savatga muvaffaqiyatli qo'shildi",
    edited: "Muvaffaqiyatli o'zgartirildi",
    slownetwork: "Sizning internetingiz ishlamayabdi yoki juda sekin ishlayabdi",
    warning: "nimadir xato ketdi qayta urinib ko'ring",
  },
  sidebar: {
    users: "Foydalanuvchilar",

    site: "Web sayt",
    mobile: "mobil",
    bot: "Bot",
    add_admin: "Admin qo'shish",
    edit_admin: "Adminni tahrirlash",
    admins: "adminlar",
    owner: "ega",
    storekeeper: "tahlovchi",
    tasischi: "tasischi",
    moliyachi: "moliyachi",
    sotuvchi: "sotuvchi",
    omborchi: "omborchi",
    prorab: "prorab",
    taminotchi: "ta'minotchi",
    kassir: "kassir",
    fullname: "to'liq ism",
    first_name: "ism",
    last_name: "familya",
    role: "roli",

    fes_warehouse_application: "FES ombor Arizasi",
    debts: "qarzlar",
    main_debt: "asosiy qarzlar",
    client_debt: "mijozlar qarzi",
    income: "Kirimlar",
    main_income: "asosiy kirimlar",
    income_dollor: "mijoz kirimlar",
    income_sum: "FES mijoz kirimlar",
    income_card: "kirim card",
    income_bank: "kirim bank",
    expenses_sum: "Asosiy Chiqimlar",
    expenses_dollor: "Yetkazib beruvchi chiqimlari",
    expenses_bank: "Chiqim Bank",
    fes: "FES",

    fes_clients: "FES mijoz",
    fes_application: "FES Arizalar",
    fes_sold: "FES jo'natmalar",
    send: "yuborish",
    shipment: "jo'natmalar",
    products: "Mahsulotlar",
    home: "Asosiy",
    delivers: "Kategoriyalar",
    orders: "Buyurtmalar",
    main_warehouse: "Brendlar",
    warehouse: "Omborxonalar",
    transfers: "O'tkazmalar",
    client: "Mijozlar",
    expenses: "Chiqmlar",
    settings: "Sozlamalar",
    sold_products: "Arizalar",
    exit: "chiqish",
    main_transfers: "Asosiy O'tkazmalar",
    warehouse_transfers: "Omborxona O'tkazmalari",
    warehouse_product: "Omborxona Mahsulotlari",
  },
  table: {
    creator: "yaratuvchi",
    ordered: "ordered",
    sale_cost: "chegirmadagi narx",
    sale_amount: "chegirma foizi",
    exist: "mavjud",
    sale: "chegirma",
    moving_from_country: "mamlakatdan chiqib ketdi",
    entered_to_country: "mamlakatga kirdi",
    delivered: "yetkazib berildi",

    types: "ko'rish filtri",
    all: "hammasi",
    by_category: "kategoriya bo'yicha",
    by_client: "mijozlar bo'yicha",
    by_fesclient: "FES mijozlar bo'yicha",
    active: "faol",
    kurs: "kurs",
    shipment_id: "jo'natma idsi",
    custom_date: "maxsus vaqt",
    residual_amount: "qisqacha ma'lumot",
    complated_amount: "Batafsil Malumot",
    complated: "tugallangan",
    image: "rasm",
    deliver_name: "yetkazib beruvchi ismi",
    deliver_phone: "yetkazib beruvchi raqami",
    truck_number: "asosiy",
    add_shipment: "Jo'natma qo'shish",
    type: "O'lchov birligi",
    name: "nomi",
    titile: "ma'lumot",
    subtitle: "qo'shimcha ma'lumot",
    info: "ma'lumot",
    created_at: "yaratilgan vaqti",
    amount: "miqdori",
    sum: "Summa",
    dollar: "valyutada",
    overall_price: "ozuqaviy ma'lumotlar",
    payed_price: "ingridentlari",
    status: "status",
    country: "Kategoriya",
    id: "id",
    seria_id: "sub",
    stock_id: "stock id",
    client_id: "mijoz idisi",
    country_number: "buyurtma raqami",
    price: "qo'shimcha sarlavha",
    inn: "INN",
    new_price: "Narxi",
    direction: "yo'nalish",
    product_name: "mahsulot nomi",
    client_name: "mijozning ismi",
    client_number: "mizoj raqami",
    phone_number: "telefon raqami",
    additional_info: "qo'shimcha ma'lumot",
    expenses_name: "xarajat nomi",
    rows_per_page: "sahifadagi qatorlar soni",
    date: "vaqti",
    total_amount: "jami miqdori:",
    status: "holati",
    direction: "yo'nalish",
    rejected: "rad etilgan",
    accepted: "qabul qilingan",
    reject: "rad etish",
    accept: "qabul qilish",
    pending: "kutilmoqda",
    warehouse: "Omborxona",
    employee: "xodim",
    location: "hudud",
  },

  home: {
    start_time: "Boshlanish vaqti",
    end_time: "tugash vaqti",
    budget: "byudjet",
    clients: "mijozlar",
    total_profit: "umumiy foyda",
    expenses: "xarajatlar",
  },

  modal: {
    add: "Qo'shish",
    addProduct: {
      addproduct: "Mahsulot qo'shish",
      editproduct: "Mahsulotni tahrirlash",
      count: "dona",
      liter: "litr",
      kg: "kg",
      meter: "metr",
      sale: "sotish",
      addtocart: "Savatga Qo'shish",
      sale_product: "Mahsulotni Sotish",
      total_price: "Umumiy Narxi",
    },
    addDeliver: {
      adddeliver: "Kategoriya qo'shish",
      editdeliver: "Kategoriyani tahrirlash",
    },
    addOrder: {
      addorder: "Navbat Qo'shish",
      editorder: "Navbatni Tahrirlash",
    },
    addWarehouse: {
      title: "Brend qo'shish",
      edit: "Brend Tahrirlash",
      transfer_from_werhouse: "Asosiy ombordan o'tkazish",
      transfer_to_werhouse: "Ombordan omborga o'tkazish",
    },
    addClient: {
      title: "Mijoz Qo'shish",
      edit: "Mijozni Tahrirlash",
    },
    addExpenses: {
      title: "Chiqim Qo'shish",
      edit: "Chiqimni Tahrirlash",
    },
    addIncome: {
      title: "Kirim Qo'shish",
      edit: "Kirimni Tahrirlash",
    },
    addCategory: {
      title: "Kategorya Qo'shish",
      subtitle: "Sub Kategorya Qo'shish",
      subedit: "Sub kategoriyani Tahrirlash",
      edit: "kategoriyani Tahrirlash",
      category: "kategoriya",
      subcategory: "sub kategoriya",
    },
    addCompany: {
      title: "Kompaniya qo'shish",
      edit: "Kompaniyani tahrirlash",
      category: "Kompaniyalar",
      subcategory: "hisob raqam",
      subtitle: "Kompaniya hisobini qo'shish",
      subedit: "Kompaniya hisobini tahrirlash",
    },
    fes: {
      AddModal: {
        type: "turi",
        power: "quvvat",
        fes_client: "FES mijoz qo'shish",
        fes_application: "FES ariza qo'shish",
        edit_fes_application: "FES mijozni tahrirlash",
        edit_fes_client: "FES arizani tahrirlash",
      },
    },
  },
};

export default header;
