const header = {
  uz: "UZ",
  ru: "RU",
  en: "EN",
  action: "действия",
  create: "создать",
  delete: "удалить",
  update: "изменить",
  basket: "корзинка",
  transfer: "трансфер",

  login: {
    welcome: "Добро пожаловать в Arifsolar!",
    title: "Логин",
    password: "Пароль",
    enter: "Вход",
    wrongpasswor: "Логин или пароль неверны! Пожалуйста, попробуйте еще раз",
  },

  alerts: {
    password_incorreect:
      "пароль неверный: пароль должен состоять как минимум из одной буквы верхнего регистра, символов и цифр должен содержать от 6 до 30 символов",
    confirmdelete: "Вы действительно хотите удалить?",
    ok: "подвердить",
    no: "отменить",
    inputError: "Входы не добавляют пустые данные",
    nodelete: "нет разрешения на удаление",
    deleted: "Успешно удалено",
    added: "Успешно добавить в корзину",
    edited: "Успешно Изменено",
    slownetwork: "Ваш интернет не работает или очень медленный",
    warning: "Что-то пошло не так. Пожалуйста, попробуйте еще раз",
  },

  home: {
    start_time: "время начала",
    end_time: "время окончания",
    budget: "бюджет",
    clients: "клиенты",
    total_profit: "общая прибыль",
    expenses: "расходы",
  },

  sidebar: {
    users: "users",
    type: "type",

    bot: "Бот",
    site: "сайт",
    mobile: "мобильный",
    add_admin: "Добавить админ",
    edit_admin: "Изменить админ",
    owner: "владелец",
    storekeeper: "кладовщик",
    tasischi: "перевозчик",
    moliyachi: "финансист",
    sotuvchi: "продавец",
    omborchi: "кладовщик",
    prorab: "прораб",
    taminotchi: "поставщик",
    kassir: "кассир",
    fullname: "Ф.И.О",
    first_name: "имя",
    last_name: "фамилия",
    role: "роль",
    sale_cost: "sale cost",
    sale_amount: "sale amount",
    admins: "admins",
    fes_warehouse_application: "Заявка на склад FES",
    debts: "долги",
    main_debt: "Основные долг",
    client_debt: "долг клиента",
    income: "приход",
    main_income: "Основные приход",
    income_dollor: "приход клиента",
    income_sum: "приход ФЭС клиента",
    income_card: "карточка дохода",
    income_bank: "банк приход",
    expenses_sum: "основной расходы ",
    expenses_dollor: "Поставщики расходы",
    expenses_bank: "расходы Bank",
    fes: "ФЭС",
    fes_clients: "ФЭС Клиенты",
    fes_application: "ФЭС Заявка",
    fes_sold: "ФЭС Отгрузка",
    shipment: "Отгрузка",
    products: "продукт",
    send: "отправлять",
    home: "Главная",
    orders: "Заказы",
    main_warehouse: "Бренды",
    warehouse: "Склад",
    transfers: "Трансферы",
    client: "Клиенты",
    expenses: "Расходы",
    settings: "Настройки",
    delivers: "Категории",
    sold_products: "Заявка",
    exit: "Выйти",
    main_transfers: "Основные трансферы",
    warehouse_transfers: "Cкладской трансферы",
    warehouse_product: "Складской товар",
  },
  table: {
    from: "from",
    lang: "lang",
    star: "star",
    moving_from_country: "переезд из страны",
    entered_to_country: "въехал в страну",
    delivered: "доставленный",
    creator: "создатель",
    ordered: "buyurtma berilgan",
    exist: "существовать",
    types: "фильтр просмотра",
    all: "все",
    by_category: "по категории",
    by_client: "по клиенту",
    by_fesclient: "по ФЭС клиенту",
    complated: "завершенный",
    active: "активный",
    kurs: "курс",
    shipment_id: "ид отправления",
    custom_date: "настраиваемое время",
    residual_amount: "краткая информация",
    complated_amount: "подробная информация",
    complated: "завершенный",
    image: "картинка",
    deliver_name: " наименование доставки",
    deliver_phone: "телефон доставки",
    truck_number: "основной",
    add_shipment: "Добавить Отгрузка",
    sum: "Сумма",
    dollar: "в валюте",
    name: "название",
    sale: "скидка",
    sale_cost: "цена со скидкой",
    sale_amount: "процент скидки",
    subtitle: "ПОДЗАГОЛОВОК",
    titile: "заголовок",
    subtitle: "информация",
    info: "информация",
    created_at: "создано в",
    amount: "количество",
    total_price: "общая цена",
    payed_price: "ингредиенты",
    status: "статус",
    country: "Категория",
    total_amount: "Общая количество",
    country_number: "номер заказа",
    id: "ид",
    client_id: "клиент ID",
    type: "car type",
    inn: "ИНН",
    overall_price: "информация о пищевой ценности",
    seria_id: "Саб",
    stock_id: "акции ид",
    price: "подзаголовок",
    new_price: " цена",
    product_name: "название продукта",
    client_name: "имя клиента",
    client_number: "номер клиента",
    phone_number: "номер телефона",
    additional_info: "дополнительная информация",
    expenses_name: "название расход",
    rows_per_page: "Строк на странице",
    date: "время",
    status: "статус",
    direction: "направление",
    rejected: "отклонено",
    accepted: "принято",
    reject: "отклонить",
    accept: "принять",
    pending: "в ожидании",
    warehouse: "Склад",
    employee: "сотрудник",
    location: "расположение",
  },
  modal: {
    add: "Добавлять",
    addProduct: {
      addproduct: "добавить продукт",
      editproduct: "изменить продукт",
      count: "штук",
      kg: "кг",
      liter: "литр",
      meter: "метр",
      sale: "продавать",
      addtocart: "добавить в корзину",
      sale_product: "Продажа продуктов",
      total_price: "общая цена",
    },
    addDeliver: {
      adddeliver: "Добавить категорию",
      editdeliver: "Изменить категорию",
    },
    addOrder: {
      addorder: "Добавить очередь",
      editorder: "Изменить очередь",
    },
    addWarehouse: {
      title: "Добавить бренд",
      edit: "Изменить бренд",
      transfer_from_werhouse: "трансфер с основного склада",
      transfer_to_werhouse: "трансфер со склада на склад",
    },
    addClient: {
      title: "Добавить клиента",
      edit: "изменить клиента",
    },
    addExpenses: {
      title: "Добавить расходы",
      edit: "изменить расходы",
    },
    addIncome: {
      title: "Добавить приход",
      edit: "изменить приход",
    },
    addCategory: {
      category: "Категория",
      subcategory: "подкатегория",
      title: "Добавить Категория",
      edit: "изменить категория",
      subtitle: "Добавить подкатегория",
      subedit: "изменить подкатегория",
    },
    addCompany: {
      title: "Добавить компанию",
      edit: "Изменить компанию",
      category: "Kомпания",
      subcategory: "номер счета",
      subtitle: "Добавить Аккаунт компании",
      subedit: "Изменить Аккаунт компании",
    },
    fes: {
      AddModal: {
        type: "тип",
        power: "мощность",
        fes_client: "Добавить ФЭС клиент ",
        fes_application: "Добавить ФЭС Заявка",
        edit_fes_application: "Изменить ФЭС Заявка ",
        edit_fes_client: "Изменить  ФЭС клиент",
      },
    },
  },
};

export default header;
