const header = {
  uz: "uz",
  ru: "ru",
  en: "en",
  action: "actions",
  create: "create",
  delete: "delete",
  update: "edit",
  basket: "Basket",
  transfer: "Transfer",
  login: {
    welcome: "Welcome to Arifsolar",
    title: "Login",
    password: "Password",
    enter: "login",
    wrongpasswor: "Username or password is incorrect! Please try again",
  },

  alerts: {
    password_incorreect:
      "password is incorrect: password must consist of at least one uppercase letter, symbol and number, must contain 6 to 30 characters",
    confirmdelete: "Are you sure you want to delete?",
    ok: "ok",
    no: "cancel",
    inputError: "Inputs do not add empty data",
    nodelete: "not permission",
    deleted: "Successfully deleted",
    added: "Successfully add to cart",
    edited: "Successfully Changed",
    slownetwork: "Your internet is down or very slow",
    warning: "something went wrong, please try again",
  },

  sidebar: {
    banners: "Banners",
    cars: "Cars",
    answers: "FAQs",
    reviews: "Reviews",
    leeds: "Leeds",
    admins: "Managers",
    mobile: "mobile",
    type: "type",
    exit: "Log out",
    role: "role",
  },

  home: {
    start_time: "start time",
    end_time: "end time",
    budget: "budget",
    clients: "clients",
    total_profit: "total profit",
    expenses: "expenses",
  },

  table: {
    lang: "lang",
    star: "star",
    from: "from",
    ordered: "ordered",
    moving_from_country: "moving from country",
    entered_to_country: "entered to country",
    delivered: "delivered",
    creator: "creator",
    types: "view filter",
    all: "all",
    by_category: "by category",
    by_client: "by client",
    by_fesclient: "by FES client",
    complated: "complated",
    active: "active",
    kurs: "kurs",
    shipment_id: "shipment id",
    custom_date: "custom time",
    residual_amount: "short info",
    complated_amount: "long info",
    complated: "completed",
    image: "picture",
    exist: "exist",
    deliver_name: " deliver name",
    deliver_phone: "deliver phone",
    truck_number: "main",
    add_shipment: "Add Shipment",
    name: "name",
    sale: "sale",
    titile: "title",
    sale_cost: "sale cost",
    sale_amount: "discount percentage",
    subtitle: "sub title",
    info: "info",
    created_at: "created at",
    amount: "amount",
    overall_price: "nutritional information",
    payed_price: "ingredients",
    status: "status",
    country: "Category",
    country_number: " order number",
    id: "id",
    inn: "INN",
    total_amount: "total amount",
    type: "тип автомобиля",
    seria_id: "sub",
    sum: "Summa",
    dollar: "in currency",
    stock_id: "stock id",
    price: "sub title",
    client_id: "client id",
    new_price: "cost",
    direction: "direction",
    product_name: "product name",
    client_name: "client name",
    client_number: "client number",
    phone_number: "phone number",
    additional_info: "additional info",
    expenses_name: "expenses name",
    rows_per_page: "Rows per page",
    date: "time",
    status: "status",
    direction: "direction",
    rejected: "rejected",
    accepted: "accepted",
    reject: "reject",
    accept: "accept",
    pending: "pending",
    warehouse: "Warehouse",
    employee: "employee",
    location: "location",
  },

  modal: {
    add: "Add",
    addProduct: {
      addproduct: "Add Product",
      editproduct: "Edit Product",
      count: "count",
      kg: "kg",
      liter: "liter",
      meter: "meter",
      sale: "sell",
      addtocart: "Add to Cart",
      sale_product: "Salle Product",
      total_price: "Total Price",
    },
    addDeliver: {
      adddeliver: "Add category",
      editdeliver: "Edit category",
    },
    addOrder: {
      addorder: "Add Order",
      editorder: "Edit Order",
    },
    addWarehouse: {
      title: "Add Brand",
      edit: "Edit Brand",
      transfer_from_werhouse: "Transfer from Main Warehouse",
      transfer_to_werhouse: "Transfer from Warehouse to Warehouse",
    },
    addClient: {
      title: "Add Client",
      edit: "Edit Client",
    },
    addExpenses: {
      title: "Add Expenses",
      edit: "Edit Expenses",
    },
    addIncome: {
      title: "Add Income",
      edit: "Edit Income",
    },
    addCategory: {
      title: "Add Category",
      edit: "Edit Category",
      category: "Category",
      subcategory: "Sub Category",
      subtitle: "Add Sub Category",
      subedit: "Edit Sub Category",
    },
    addCompany: {
      title: "Add Company",
      edit: "Edit Company",
      category: "Company",
      subcategory: "account number",
      subtitle: "Add Company Account",
      subedit: "Edit Company Account",
    },
    fes: {
      AddModal: {
        type: "type",
        power: "Power",
        fes_client: "Add FES Client",
        fes_application: "Add FES Application",
        edit_fes_application: "Edit FES Application",
        edit_fes_client: "Edit FES Client",
      },
    },
  },
};

export default header;
